name: ReconBot Shell CI

on:
  push:
    branches:
      - main

jobs:
  run-recon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make recon.sh executable
      run: chmod +x recon.sh

    - name: Run recon bot
      run: ./recon.sh
