name: ReconBot CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # allow committing back

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go (for httpx, nuclei, gowitness)
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install recon dependencies
      run: |
        sudo apt update
        sudo apt install -y chromium-browser ffuf nmap unzip wget
        go install github.com/projectdiscovery/httpx/cmd/httpx@latest
        go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
        go install github.com/sensepost/gowitness@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH
        mkdir -p $HOME/nuclei-templates
        nuclei -update-templates || true

    - name: Make recon script executable
      run: chmod +x recon-bot.sh

    - name: Run recon bot
      run: ./recon-bot.sh juice-shop.herokuapp.com

    - name: Zip report results
      run: |
        REPORT_DIR=$(find recon-output -type d -name "*juice-shop*")
        zip -r recon-report.zip "$REPORT_DIR"

    - name: Upload recon report artifact
      uses: actions/upload-artifact@b83d6e00853fdb1f9b71863ab3dfac4301d635d3
      with:
        name: recon-report
        path: recon-report.zip

    - name: Commit report.md back to repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        REPORT_PATH=$(find recon-output -type f -name report.md)
        DEST="reports/recon-report-${GITHUB_RUN_NUMBER}.md"
        mkdir -p reports
        cp "$REPORT_PATH" "$DEST"
        git add "$DEST"
        git commit -m "Add recon report for run #${GITHUB_RUN_NUMBER}"
        git push origin main
